logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: "%(asctime)s %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    error:
#      format: "%(asctime)s %(name)s %(levelname)s %(filename)s::%(funcName)s[%(lineno)d]:%(message)s"
      format: "[%(asctime)s] [%(process)d:%(processName)s] [%(thread)d:%(threadName)s] [%(levelname)s] %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: error
      stream: ext://sys.stdout

    debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: error
      filename: ./logs/{chat_channel}/debug.log
      #      filename: ./logs/info.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: error
      filename: ./logs/{chat_channel}/info.log
#      filename: ./logs/info.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: error
#      filename: ./logs/error.log
      filename: ./logs/{chat_channel}/error.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

  root:
    level: INFO
    handlers: [console, debug_file_handler, info_file_handler, error_file_handler]

groups:
  enable: [43741496000@chatroom]  # 允许响应的群 roomId，大概长这样：2xxxxxxxxx3@chatroom

news:
  receivers: []  # 定时新闻接收人（roomid 或者 wxid）

report_reminder:
  receivers: []  # 定时日报周报月报提醒（roomid 或者 wxid）

chatgpt:  # -----chatgpt配置这行不填-----
  key:
  api: https://api.openai.com/v1  # 如果你不知道这是干嘛的，就不要改
  model: gpt-3.5-turbo
  proxy:  # 如果你在国内，你可能需要魔法，大概长这样：http://域名或者IP地址:端口号
  prompt: 你是智能聊天机器人，你叫 wcferry  # 根据需要对角色进行设定

chatglm:  # -----chatglm配置这行不填-----
  key: sk-012345678901234567890123456789012345678901234567 # 这个应该不用动
  api: http://localhost:8000/v1  # 根据自己的chatglm地址修改
  proxy:  # 如果你在国内，你可能需要魔法，大概长这样：http://域名或者IP地址:端口号
  prompt: 你是智能聊天机器人，你叫小薇  # 根据需要对角色进行设定 
  file_path: F:/Pictures/temp  #设定生成图片和代码使用的文件夹路径

tigerbot:  # -----tigerbot配置这行不填-----
  key:  # key
  model:  # tigerbot-7b-sft

xinghuo_web:  # -----讯飞星火web模式api配置这行不填 抓取方式详见文档：https://www.bilibili.com/read/cv27066577-----
  cookie:  # cookie
  fd:  # fd
  GtToken:  # GtToken
  prompt: 你是智能聊天机器人，你叫 wcferry。请用这个角色回答我的问题  # 根据需要对角色进行设定

bard: # -----bard配置这行不填-----
  api_key: AIzaSyB8HiKWUsruBBwxbby4BDAEdaDdw8eBTdY
  model_name: gemini-pro # 新模型上线后可以选择模型
  proxy: http://10.22.41.206:7892  # 如果你在国内，你可能需要魔法，大概长这样：http://域名或者IP地址:端口号
  # 提示词尽可能用英文，bard对中文提示词的效果不是很理想，下方提示词为英语老师的示例，请按实际需要修改,默认设置的提示词为谷歌创造的AI大语言模型
  # I want you to act as a spoken English teacher and improver. I will speak to you in English and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the reply to 100 words. I want you to strictly correct my grammar mistakes, typos, and factual errors. I want you to ask me a question in your reply. Now let's start practicing, you could ask me a question first. Remember, I want you to strictly correct my grammar mistakes, typos, and factual errors.
  prompt: You am a large language model, trained by Google.

zhipu:  # -----zhipu配置这行不填-----
  api_key:  #api key
  model:   # 模型类型

giiso:
  base_url: "https://ag.giiso.com/capi"
  # base_url: "https://ag-test.giiso.com/capi"
  # chat_channel: "wework"
  chat_channel: "wechat"

wechat_robot:
  robot_key: "app-vRbcS2P7iwI5JFjdbdGhIy0I"
  webhook: "https://api.dify.ai/v1"
